<?php
if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5bf675674bf88',
			'title'                 => 'Flexible Inhalte CAB',
			'fields'                => array(
				array(
					'key'               => 'field_5bf675bfa7de1',
					'label'             => 'Flexible Inhalte',
					'name'              => 'flexible',
					'type'              => 'flexible_content',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layouts'           => array(
						'5bf675d976901'        => array(
							'key'        => '5bf675d976901',
							'name'       => 'editor',
							'label'      => 'Editor',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5bf6762fa7de2',
									'label'             => 'Editor',
									'name'              => 'editor',
									'type'              => 'wysiwyg',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'tabs'              => 'all',
									'toolbar'           => 'basic',
									'media_upload'      => 0,
									'delay'             => 0,
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_5bf6769ea7de4' => array(
							'key'        => 'layout_5bf6769ea7de4',
							'name'       => 'text_and_image',
							'label'      => 'Text und Bild',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5c34a49664e4e',
									'label'             => 'Texteditor',
									'name'              => 'text',
									'type'              => 'wysiwyg',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'tabs'              => 'all',
									'toolbar'           => 'basic',
									'media_upload'      => 0,
									'delay'             => 0,
								),
								array(
									'key'               => 'field_5bf676bca7de5',
									'label'             => 'Ausrichtung',
									'name'              => 'img_dir',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'left'   => 'links',
										'right'  => 'rechts',
										'center' => 'zentriert',
									),
									'default_value'     => array(),
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'return_format'     => 'value',
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_5bf678d9a7de6',
									'label'             => 'Bild',
									'name'              => 'img',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
									'preview_size'      => 'thumbnail',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_5bf67997a7de7' => array(
							'key'        => 'layout_5bf67997a7de7',
							'name'       => 'gallery',
							'label'      => 'Galerie',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5bf679c4a7de8',
									'label'             => 'Galerie',
									'name'              => 'gallery',
									'type'              => 'gallery',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'min'               => '',
									'max'               => '',
									'insert'            => 'append',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_5bf67a57a7de9' => array(
							'key'        => 'layout_5bf67a57a7de9',
							'name'       => 'video',
							'label'      => 'Video',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5bf67d94a7ded',
									'label'             => 'Titel',
									'name'              => 'caption',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5c3ca0cc179d2',
									'label'             => 'Vorschaubild',
									'name'              => 'poster',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
									'preview_size'      => 'thumbnail',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
								array(
									'key'               => 'field_5bf67a8da7dea',
									'label'             => 'Videotyp',
									'name'              => 'type',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'online' => 'online',
										'local'  => 'lokal',
									),
									'default_value'     => array(),
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'return_format'     => 'value',
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_5bf67b1da7deb',
									'label'             => 'URL',
									'name'              => 'url',
									'type'              => 'oembed',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_5bf67a8da7dea',
												'operator' => '==',
												'value'    => 'online',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'width'             => '',
									'height'            => '',
								),
								array(
									'key'               => 'field_5bf67b61a7dec',
									'label'             => 'Datei',
									'name'              => 'file',
									'type'              => 'file',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_5bf67a8da7dea',
												'operator' => '==',
												'value'    => 'local',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
									'library'           => 'all',
									'min_size'          => '',
									'max_size'          => '',
									'mime_types'        => 'mp4',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_5bf67f12a7dee' => array(
							'key'        => 'layout_5bf67f12a7dee',
							'name'       => 'tiles',
							'label'      => 'Kacheln',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5bf67f35a7def',
									'label'             => 'Kacheln',
									'name'              => 'tiles',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 0,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => 'Kachel hinzufügen',
									'sub_fields'        => array(
										array(
											'key'          => 'field_5c0e708f72c3d',
											'label'        => 'Farbe',
											'name'         => 'color',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												': weiß' => ': weiß',
												'turquoise' => 'türkis',
											),
											'default_value' => array(),
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
										),
										array(
											'key'          => 'field_5bf681a4a7df2',
											'label'        => 'Logo',
											'name'         => 'logo',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'project'  => 'Das Projekt',
												'plain-language' => 'Leichte Sprache',
												'news'     => 'Neuigkeiten',
												'calendar' => 'Termine',
												'number-mail' => 'E-Mail und Telefonnummer',
												'participate' => 'Mitmachen',
											),
											'default_value' => array(),
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
										),
										array(
											'key'          => 'field_5bf67f74a7df0',
											'label'        => 'Titel',
											'name'         => 'title',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_5c3c4a94c4ec4',
											'label'        => 'Untertitel',
											'name'         => 'subtitle',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_5bf67faea7df1',
											'label'        => 'Link',
											'name'         => 'link',
											'type'         => 'page_link',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'post_type'    => array(
												0 => 'page',
											),
											'taxonomy'     => '',
											'allow_null'   => 0,
											'allow_archives' => 0,
											'multiple'     => 0,
										),
									),
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_5c349fb7279da' => array(
							'key'        => 'layout_5c349fb7279da',
							'name'       => 'downloads',
							'label'      => 'Downloads',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5c34a044279db',
									'label'             => 'Downloads',
									'name'              => 'downloads',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 0,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => 'Download hinzufügen',
									'sub_fields'        => array(
										array(
											'key'          => 'field_5c34a08f279dc',
											'label'        => 'Titel',
											'name'         => 'title',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_5c34a0dc279dd',
											'label'        => 'Datei',
											'name'         => 'file',
											'type'         => 'file',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'return_format' => 'array',
											'library'      => 'all',
											'min_size'     => '',
											'max_size'     => '',
											'mime_types'   => '',
										),
									),
								),
							),
							'min'        => '',
							'max'        => '',
						),
					),
					'button_label'      => 'Inhalt hinzufügen',
					'min'               => '',
					'max'               => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'page',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'post',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'acf_after_title',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0 => 'the_content',
			),
			'active'                => 1,
			'description'           => '',
		)
	);

endif;
